- name: Set server timezone to {{ koha_server_timezone }}
  timezone:
    name: "{{ koha_server_timezone }}"
  when: koha_server_timezone|default(False)|bool

- name: Add Koha package repository signing key
  apt_key:
    keyserver: "{{ koha_keyserver }}"
    id: "{{ koha_signing_key_id }}"

- name: Add Koha package repository
  apt_repository:
    repo: "{{ koha_package_repository }}"
    state: present
    filename: koha-packages

- name: Install Koha packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - koha-common
    - koha-elasticsearch

- name: Check to have {{ koha_domain }} domain in /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ koha_domain }}"
    state: present

- name: Enable required Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - cgi
    - headers
    - proxy_http
    - ssl
  register: apache_modules

- name: Assign 'koha user exists' test variable
  set_fact: koha_user_exists_error_message="User {{ koha_instance_name }}-koha already exists"
  when: koha_create_instance|bool

- name: Create Koha instance
  command: koha-create {{ koha_instance_name }} --use-db --database {{ koha_db_database }}
  register: koha_create_result
  failed_when: 
    - koha_create_result.rc != 0
    - 'koha_user_exists_error_message not in koha_create_result.stderr'
  changed_when: "koha_user_exists_error_message not in koha_create_result.stderr"
  when: koha_create_instance|bool

- name: Configure koha-conf.xml
  template:
    src: koha-conf.xml.j2
    dest: /etc/koha/sites/{{ koha_instance_name }}/koha-conf.xml
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: koha_conf

- name: Check for fi-FI translation
  command: koha-translate --list
  failed_when: False
  register: koha_installed_translations
  changed_when: '"fi-FI" not in koha_installed_translations.stdout'
  when: koha_install_fi_translation

- name: Install fi-FI translation
  shell: "koha-translate --install fi-FI || koha-translate --update fi-FI"
  when: koha_install_fi_translation and koha_installed_translations.changed
  register: koha_lng_install
  failed_when: 
    # TODO: this is temporary workaround with stderr check below:
    #       should be reworked by committing fix to KohaCommuity bugzilla:
    #       seems koha-translate installator uses regular libraries 
    #       and tends to connect/chek for __MEMCACHED_SERVERS__
    - koha_lng_install.stderr != "\nConnection to the memcached servers '__MEMCACHED_SERVERS__' failed. Are the unix socket permissions set properly? Is the host reachable?\nIf you ignore this warning, you will face performance issues\n\nConnection to the memcached servers '__MEMCACHED_SERVERS__' failed. Are the unix socket permissions set properly? Is the host reachable?\nIf you ignore this warning, you will face performance issues\n\nConnection to the memcached servers '__MEMCACHED_SERVERS__' failed. Are the unix socket permissions set properly? Is the host reachable?\nIf you ignore this warning, you will face performance issues"
    - koha_lng_install.rc != 0

  # TODO: might be another action for "update" if installed:
  # koha-translate --update fi-FI 

- name: Enable Plack
  command: koha-plack --enable {{ koha_instance_name }}
  register: koha_plack_result
  failed_when:
    - koha_plack_result.rc != 0
    - '"Plack already enabled for" not in koha_plack_result.stderr'
  changed_when: '"Plack already enabled for" not in koha_plack_result.stderr'

- name: Configure apache2
  template:
    src: apache-conf.j2
    dest: /etc/apache2/sites-enabled/{{ koha_instance_name }}.conf
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: apache_conf

- name: Configure SIPconfig.xml
  template:
    src: SIPconfig.xml.j2
    dest: /etc/koha/sites/{{ koha_instance_name }}/SIPconfig.xml
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: koha_sip_conf
  when: koha_sip_enable

- name: Enable SIP server
  command: koha-enable-sip {{ koha_instance_name }}
  register: koha_sip_result
  changed_when: '"SIP server already enabled" not in koha_sip_result.stdout'
  when: koha_sip_enable

- name: Restart koha-common
  systemd:
    state: restarted
    name: koha-common
  when: koha_conf.changed or koha_sip_conf.changed or koha_sip_result.changed

- name: Restart memcached
  systemd:
    state: restarted
    name: memcached
  when: koha_conf.changed

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
  when: apache_modules.changed or koha_plack_result.changed or apache_conf.changed
