- name: Set server timezone to {{ koha_server_timezone }}
  timezone:
    name: "{{ koha_server_timezone }}"
  when: koha_server_timezone|default(False)|bool

- name: Add Koha package repository signing key
  apt_key:
    keyserver: "{{ koha_keyserver }}"
    id: "{{ koha_signing_key_id }}"

- name: Add Koha package repository
  apt_repository:
    repo: "{{ koha_package_repository }}"
    state: present
    filename: koha-packages

- name: Install Koha packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - koha-common
    - koha-elasticsearch

- name: Enable required Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - cgi
    - headers
    - proxy_http
    - ssl
  register: apache_modules

- name: Create Koha instance
  command: koha-create {{ koha_instance_name }} --use-db --database {{ koha_db_database }}
  when: koha_create_instance

- name: Configure koha-conf.xml
  template:
    src: koha-conf.xml.j2
    dest: /etc/koha/sites/{{ koha_instance_name }}/koha-conf.xml
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: koha_conf

- name: Enable Plack
  command: koha-plack --enable {{ koha_instance_name }}
  ignore_errors: true
  register: koha_plack_result
  changed_when: '"Plack enabled for" in koha_plack_result.stdout'

- name: Configure apache2
  template:
    src: apache-conf.j2
    dest: /etc/apache2/sites-enabled/{{ koha_instance_name }}.conf
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: apache_conf

- name: Configure SIPconfig.xml
  template:
    src: SIPconfig.xml.j2
    dest: /etc/koha/sites/{{ koha_instance_name }}/SIPconfig.xml
    owner: root
    group: "{{ koha_instance_name }}-koha"
    mode: u=rw,g=r
  register: koha_sip_conf
  when: koha_sip_enable

- name: Enable SIP server
  command: koha-enable-sip {{ koha_instance_name }}
  register: koha_sip_result
  changed_when: '"SIP server already enabled" not in koha_sip_result.stdout'
  when: koha_sip_enable

- name: Restart koha-common
  systemd:
    state: restarted
    name: koha-common
  when: koha_conf.changed or koha_sip_conf.changed or koha_sip_result.changed

- name: Restart memcached
  systemd:
    state: restarted
    name: memcached
  when: koha_conf.changed

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
  when: apache_modules.changed or koha_plack_result.changed or apache_conf.changed
